apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ax4j
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-ax4j@sha256:ed0f78344458a8155f16b11bc2e9fbac8d13f74276f33a1382900ec9180edf51
        name: my-nodejs
        resources: {}
status: {}
